/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.controladorAgregar;
import Controlador.controladorBuscar;
import Controlador.controladorEliminar;
import Controlador.controladorMostrar;
import Modelo.Conexion;
import Modelo.ConsultasLibro;
import Modelo.Libro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felipealvarezbenitez
 */
public class frmBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmBiblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnIrEliminar = new javax.swing.JButton();
        btnIrAgregar = new javax.swing.JButton();
        btnIrBuscar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMostrar = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Nombre de la Biblioteca");

        btnIrEliminar.setText("Eliminar");
        btnIrEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrEliminarActionPerformed(evt);
            }
        });

        btnIrAgregar.setText("Agregar");
        btnIrAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAgregarActionPerformed(evt);
            }
        });

        btnIrBuscar.setText("Buscar");
        btnIrBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrBuscarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar ");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        tablaMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaMostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIrAgregar)
                                .addGap(62, 62, 62)
                                .addComponent(btnIrEliminar)
                                .addGap(64, 64, 64)
                                .addComponent(btnIrBuscar))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnMostrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrAgregar)
                    .addComponent(btnIrEliminar)
                    .addComponent(btnIrBuscar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnMostrar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAgregarActionPerformed
        /*this.setVisible(false);
        agg.setVisible(true);
        */
        frmAgregar frmA = new frmAgregar();
        ConsultasLibro conLibro = new ConsultasLibro();
        Libro libros = new Libro();
        controladorAgregar agregar = new controladorAgregar(libros, conLibro, frmA);
        agregar.iniciar();
        frmA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrAgregarActionPerformed

    private void btnIrEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrEliminarActionPerformed
        /*this.setVisible(false);
        eliminar.setVisible(true);
        */
        ConsultasLibro conLibro = new ConsultasLibro();
        Libro libros = new Libro();
        frmEliminar frmE = new frmEliminar();
        controladorEliminar eliminar = new controladorEliminar(libros, conLibro, frmE);
        eliminar.iniciar();
        frmE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrEliminarActionPerformed

    private void btnIrBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrBuscarActionPerformed
       /* this.setVisible(false);
        buscar.setVisible(true);
        */
        ConsultasLibro conLibro = new ConsultasLibro();
        Libro libros = new Libro();
        frmBuscar frmB = new frmBuscar();
        controladorBuscar buscar = new controladorBuscar(libros, conLibro, frmB);
        buscar.iniciar();
        frmB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrBuscarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed

        try{
            DefaultTableModel model = new DefaultTableModel();
            tablaMostrar.setModel(model);
            PreparedStatement ps;
            ResultSet rs;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion(); 
            
            String sql = "SELECT titulo, nombreAutor,categoria FROM mydb.libros";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            model.addColumn("Titulo");
            model.addColumn("Nombre Autor");
            model.addColumn("Categoria");
            
            while(rs.next()){
                
                Object [] filas = new Object[cantidadColumnas];
                
                for(int i = 0; i < cantidadColumnas; i++){
                    
                    filas[i] = rs.getObject(i + 1);
                    
                }
                model.addRow(filas); 
            }
        }catch(SQLException e){            
            System.err.print(e); 
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIrAgregar;
    public javax.swing.JButton btnIrBuscar;
    public javax.swing.JButton btnIrEliminar;
    public javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable tablaMostrar;
    // End of variables declaration//GEN-END:variables
}
